[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "src/1/main.rs"

[[bin]]
name = "2"
path = "src/2/main.rs"

[[bin]]
name = "3"
path = "src/3/main.rs"

[[bin]]
name = "4"
path = "src/4/main.rs"

[dependencies]
itertools = "0.10.5"
